const mentirosoPhrases = {
    'Facil': [
        // --- 1. Trofeos y Hitos Mayores ---
        "Selecciones que hayan ganado la Copa Mundial de la FIFA",
        "Jugadores que hayan ganado el Balón de Oro",
        "Equipos que hayan ganado la UEFA Champions League",
        "Países sudamericanos que hayan jugado un Mundial",
        "Clubes con más de 10 títulos de Liga en su país",
        "Posiciones en el campo de fútbol",
        "Grandes estadios de fútbol",
        "Jugadores que hayan marcado más de 50 goles en La Liga",
        "Jugadores que hayan ganado la Premier League",
        "Equipos que hayan ganado la Copa América",
        // --- 2. Figuras Clave ---
        "Técnicos que hayan dirigido a la Selección Argentina",
        "Jugadores brasileños campeones del mundo",
        "Jugadores argentinos campeones del mundo en 1986",
        "Jugadores que hayan ganado el Mundial y la Eurocopa/Copa América",
        "Goleadores de la historia del Clásico Español",
        "Futbolistas que hayan jugado en el FC Barcelona",
        "Futbolistas que hayan jugado en el Real Madrid",
        "Jugadores que hayan ganado el triplete (Liga, Copa, Champions)",
        "Arqueros históricos",
        "Defensores centrales legendarios",
        // --- 3. Conceptos Básicos ---
        "Tipos de tarjetas arbitrales",
        "Términos técnicos del fútbol",
        "Clubes que hayan jugado la final de la Copa Libertadores",
        "Selecciones europeas campeonas del mundo",
        "Jugadores que hayan ganado el premio The Best de la FIFA",
        "Clubes fundadores de la liga de su país",
        "Jugadores que hayan superado los 100 partidos con su selección",
        "Clubes que hayan ganado el Mundial de Clubes",
        "Capitanes icónicos de equipos europeos",
        "Entrenadores que hayan ganado la Champions League"
    ],
    'Mediano': [
        // --- 1. Récords y Estadísticas Específicas ---
        "Jugadores que hayan ganado la Bota de Oro Europea",
        "Goleadores históricos de la Copa Mundial de la FIFA",
        "Clubes que hayan ganado la Copa Intercontinental/Mundial de Clubes",
        "Jugadores que hayan ganado la Copa Libertadores con dos clubes distintos",
        "Selecciones que hayan jugado la final de la Copa América sin ganarla",
        "Jugadores que hayan marcado un 'Hat-trick' en un Clásico",
        "Futbolistas que hayan jugado más de 5 Mundiales",
        "Goleadores de la Copa América con más de 10 goles",
        "Jugadores que hayan marcado 4 o más goles en un partido de Mundial",
        "Ciudades que hayan albergado finales de la Copa Mundial de la FIFA",
        // --- 2. Figuras Menos Evidentes y Hitos de Torneos ---
        "Clubes que hayan ganado la Copa UEFA/Europa League",
        "Árbitros famosos y/o polémicos de Mundiales",
        "Jugadores que hayan ganado el Premio Puskás al mejor gol",
        "Jugadores que hayan sido Pichichi y Zamora en la misma temporada",
        "Futbolistas que hayan jugado en Boca Juniors y River Plate",
        "Selecciones que hayan ganado medalla de oro en fútbol olímpico",
        "Clubes que hayan descendido tras haber sido campeones de su liga",
        "Jugadores que hayan ganado la Copa Confederaciones",
        "Futbolistas que hayan marcado gol en 4 Mundiales distintos",
        "Entrenadores que hayan ganado la Champions League con dos clubes distintos",
        // --- 3. Clubes y Ligas Específicas ---
        "Clubes que hayan ganado la liga de su país invictos",
        "Goleadores históricos de la Serie A italiana",
        "Clubes que hayan jugado más de 10 finales de Copa Libertadores",
        "Jugadores que hayan debutado antes de los 16 años en ligas importantes",
        "Presidentes de clubes legendarios",
        "Jugadores que hayan marcado más de 100 goles en la Bundesliga",
        "Entrenadores que hayan dirigido más de 500 partidos en una misma liga",
        "Estadios con más de 80.000 espectadores",
        "Jugadores que hayan ganado el Premio Golden Boy",
        "Clubes que hayan ganado la Recopa de Europa (antiguo torneo)"
    ],
    'Dificil': [
        // --- 1. Récords Mundiales y Combinaciones Raras ---
        "Selecciones que hayan jugado la final de la Copa Confederaciones",
        "Goleadores del Mundial 2002",
        "Jugadores que hayan ganado la Copa del Mundo, la Champions League y el Balón de Oro",
        "Jugadores que hayan ganado la Bota de Oro de la Premier League con más de 30 goles",
        "Clubes europeos que hayan ganado la Copa de Ferias (precursora de la UEFA/Europa League)",
        "Futbolistas que hayan sido transferidos por más de 100 millones de euros",
        "Presidentes de la FIFA",
        "Jugadores que hayan marcado más de 10 goles con su selección en un año calendario",
        "Entrenadores que hayan ganado la Copa Libertadores y la Champions League (Solo hay 2: Carlo Ancelotti, José Mourinho)",
        "Jugadores que hayan marcado un 'Gol Olímpico' en un Mundial",
        // --- 2. Goles y Estadísticas Extremas ---
        "Goleadores del Mundial 1950",
        "Clubes que hayan ganado el título de liga con 100 o más puntos",
        "Jugadores que hayan marcado 5 o más goles en un solo partido de Champions League",
        "Entrenadores que hayan ganado la Champions League y la Copa Libertadores",
        "Clubes que hayan ganado todos los títulos continentales posibles",
        "Jugadores que hayan ganado el premio a 'Mejor Jugador Joven' en un Mundial",
        "Selecciones de CONCACAF que hayan llegado a semifinales de un Mundial",
        "Jugadores que hayan ganado el 'Doblete' de Balones de Oro y Plata en un mismo Mundial",
        "Futbolistas que hayan marcado en finales de Copa del Mundo, Eurocopa y Champions League",
        "Goleadores de la Liga de Campeones con clubes no tradicionales",
        // --- 3. Clubes, Ligas y Logros Antiguos/Raros ---
        "Clubes que hayan ganado la Copa Mitropa (antiguo torneo centroeuropeo)",
        "Países que hayan ganado la Copa Kirin (torneo amistoso)",
        "Clubes que hayan ganado la Copa Intertoto de la UEFA (antiguo torneo de verano)",
        "Jugadores que hayan jugado en los 5 grandes de Italia (Juventus, Milan, Inter, Roma, Napoli)",
        "Jugadores que hayan marcado un gol de chilena en la final de un torneo continental",
        "Clubes que hayan ganado la liga de su país por única vez en la historia",
        "Jugadores con más partidos en la historia de la Copa Libertadores",
        "Futbolistas que hayan ganado el triplete con clubes de ligas diferentes",
        "Selecciones que hayan jugado la final del Mundial y hayan quedado eliminadas en fase de grupos al siguiente",
        "Entrenadores que hayan ganado 3 o más Copas de Europa con un solo club"
    ]
};